# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QtFormDeCoder.ui'
#
# Created by: PyQt5 UI code generator 5.13.1
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(10, 10, 780, 22))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        self.comboBox.setSizePolicy(sizePolicy)
        self.comboBox.setObjectName("comboBox")
        self.label1 = QtWidgets.QLabel(self.centralwidget)
        self.label1.setGeometry(QtCore.QRect(10, 60, 30, 22))
        self.label1.setObjectName("label1")
        self.line1 = QtWidgets.QFrame(self.centralwidget)
        self.line1.setGeometry(QtCore.QRect(10, 40, 781, 16))
        self.line1.setFrameShape(QtWidgets.QFrame.HLine)
        self.line1.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line1.setObjectName("line1")
        self.lineEdit1 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit1.setGeometry(QtCore.QRect(40, 60, 60, 22))
        self.lineEdit1.setObjectName("lineEdit1")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(10, 90, 111, 16))
        self.label.setObjectName("label")
        self.pushButton1 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton1.setGeometry(QtCore.QRect(330, 60, 460, 28))
        self.pushButton1.setObjectName("pushButton1")
        self.label2 = QtWidgets.QLabel(self.centralwidget)
        self.label2.setGeometry(QtCore.QRect(120, 60, 30, 22))
        self.label2.setObjectName("label2")
        self.lineEdit2 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit2.setGeometry(QtCore.QRect(150, 60, 60, 22))
        self.lineEdit2.setObjectName("lineEdit2")
        self.pushButton2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton2.setGeometry(QtCore.QRect(330, 210, 460, 28))
        self.pushButton2.setObjectName("pushButton2")
        self.label3 = QtWidgets.QLabel(self.centralwidget)
        self.label3.setGeometry(QtCore.QRect(224, 60, 30, 22))
        self.label3.setObjectName("label3")
        self.lineEdit3 = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit3.setGeometry(QtCore.QRect(254, 60, 60, 22))
        self.lineEdit3.setObjectName("lineEdit3")
        self.label4 = QtWidgets.QLabel(self.centralwidget)
        self.label4.setGeometry(QtCore.QRect(330, 120, 191, 16))
        self.label4.setObjectName("label4")
        self.label5 = QtWidgets.QLabel(self.centralwidget)
        self.label5.setGeometry(QtCore.QRect(330, 280, 191, 16))
        self.label5.setObjectName("label5")
        self.label6 = QtWidgets.QLabel(self.centralwidget)
        self.label6.setGeometry(QtCore.QRect(330, 360, 151, 16))
        self.label6.setObjectName("label6")
        self.line3 = QtWidgets.QFrame(self.centralwidget)
        self.line3.setGeometry(QtCore.QRect(330, 100, 460, 16))
        self.line3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line3.setObjectName("line3")
        self.tableWidget = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget.setGeometry(QtCore.QRect(10, 110, 304, 460))
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.setColumnCount(0)
        self.tableWidget.setRowCount(0)
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setDefaultSectionSize(30)
        self.tableWidget.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget1 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget1.setGeometry(QtCore.QRect(330, 140, 460, 60))
        self.tableWidget1.setObjectName("tableWidget1")
        self.tableWidget1.setColumnCount(0)
        self.tableWidget1.setRowCount(0)
        self.tableWidget1.horizontalHeader().setVisible(False)
        self.tableWidget1.horizontalHeader().setDefaultSectionSize(30)
        self.tableWidget1.horizontalHeader().setHighlightSections(True)
        self.tableWidget1.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget1.verticalHeader().setVisible(False)
        self.tableWidget1.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget2 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget2.setGeometry(QtCore.QRect(330, 300, 460, 60))
        self.tableWidget2.setObjectName("tableWidget2")
        self.tableWidget2.setColumnCount(0)
        self.tableWidget2.setRowCount(0)
        self.tableWidget2.horizontalHeader().setVisible(False)
        self.tableWidget2.horizontalHeader().setDefaultSectionSize(30)
        self.tableWidget2.horizontalHeader().setHighlightSections(True)
        self.tableWidget2.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget2.verticalHeader().setVisible(False)
        self.tableWidget2.verticalHeader().setDefaultSectionSize(30)
        self.tableWidget3 = QtWidgets.QTableWidget(self.centralwidget)
        self.tableWidget3.setGeometry(QtCore.QRect(330, 380, 460, 60))
        self.tableWidget3.setObjectName("tableWidget3")
        self.tableWidget3.setColumnCount(0)
        self.tableWidget3.setRowCount(0)
        self.tableWidget3.horizontalHeader().setVisible(False)
        self.tableWidget3.horizontalHeader().setDefaultSectionSize(30)
        self.tableWidget3.horizontalHeader().setHighlightSections(True)
        self.tableWidget3.horizontalHeader().setMinimumSectionSize(30)
        self.tableWidget3.verticalHeader().setVisible(False)
        self.tableWidget3.verticalHeader().setDefaultSectionSize(30)
        self.label7 = QtWidgets.QLabel(self.centralwidget)
        self.label7.setGeometry(QtCore.QRect(330, 250, 191, 22))
        self.label7.setObjectName("label7")
        self.lineEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.lineEdit.setGeometry(QtCore.QRect(540, 250, 61, 22))
        self.lineEdit.setObjectName("lineEdit")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.comboBox.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Помехозащитное кодирование: совершенные и квазисовершенные коды - DeCoder"))
        self.label1.setText(_translate("MainWindow", "m = "))
        self.lineEdit1.setText(_translate("MainWindow", "lineEdit1"))
        self.label.setText(_translate("MainWindow", "Матрица M (n x r)"))
        self.pushButton1.setText(_translate("MainWindow", "Шаг 1: Установка параметров"))
        self.label2.setText(_translate("MainWindow", "n = "))
        self.lineEdit2.setText(_translate("MainWindow", "lineEdit2"))
        self.pushButton2.setText(_translate("MainWindow", "Шаг 2: Декодирование"))
        self.label3.setText(_translate("MainWindow", "r = "))
        self.lineEdit3.setText(_translate("MainWindow", "lineEdit3"))
        self.label4.setText(_translate("MainWindow", "Полученное сообщение (b + e)"))
        self.label5.setText(_translate("MainWindow", "Исправленное сообщение (b)"))
        self.label6.setText(_translate("MainWindow", "Исходное сообщение (a)"))
        self.label7.setText(_translate("MainWindow", "Ошибка в позиции ((b + e) x M)"))
        self.lineEdit.setText(_translate("MainWindow", "lineEdit"))
